// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbiw8foxRgTONmVd9zbi1uBfDRTcg39i4',
    appId: '1:11028150820:web:c2a7d95dbf506ef862f6b1',
    messagingSenderId: '11028150820',
    projectId: 'taskmanager-e70fc',
    authDomain: 'taskmanager-e70fc.firebaseapp.com',
    storageBucket: 'taskmanager-e70fc.firebasestorage.app',
    measurementId: 'G-0P3S3ZCLKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbiV6oJIxxtKbDomtDubgQsUaTeS6dz5g',
    appId: '1:11028150820:android:5cbb99ae1aa3fd5062f6b1',
    messagingSenderId: '11028150820',
    projectId: 'taskmanager-e70fc',
    storageBucket: 'taskmanager-e70fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyXe6Sxs5-OXWR7hhummRCkp5aFZqCo9Y',
    appId: '1:11028150820:ios:6b24a59245a824b762f6b1',
    messagingSenderId: '11028150820',
    projectId: 'taskmanager-e70fc',
    storageBucket: 'taskmanager-e70fc.firebasestorage.app',
    iosClientId: '11028150820-214t4uugciko9ppg6tvdenkj2j7jpfb8.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyXe6Sxs5-OXWR7hhummRCkp5aFZqCo9Y',
    appId: '1:11028150820:ios:6b24a59245a824b762f6b1',
    messagingSenderId: '11028150820',
    projectId: 'taskmanager-e70fc',
    storageBucket: 'taskmanager-e70fc.firebasestorage.app',
    iosClientId: '11028150820-214t4uugciko9ppg6tvdenkj2j7jpfb8.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbiw8foxRgTONmVd9zbi1uBfDRTcg39i4',
    appId: '1:11028150820:web:cb7305497cd5145262f6b1',
    messagingSenderId: '11028150820',
    projectId: 'taskmanager-e70fc',
    authDomain: 'taskmanager-e70fc.firebaseapp.com',
    storageBucket: 'taskmanager-e70fc.firebasestorage.app',
    measurementId: 'G-YDMS4FV4E9',
  );
}
